fail_fast: true
repos:
  - repo: local
    hooks:
      - id: qc
        name: Quality & style check
        entry: task check
        language: system
        always_run: true
        pass_filenames: false
      - id: cs
        name: Black style fix
        entry: task fix
        language: system
        always_run: true
        pass_filenames: false
